[package]
name = "minecraft-2d"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28"
noise = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["std"] }
rmp-serde = "1.3"
functionality = "1"
dirs = "6.0"
