[package]
name = "minecraft-2d"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.28"
dirs = "6.0"
functionality = "1"
noise = "0.9"
rmp-serde = "1.3"
serde = { version = "1.0", features = ["derive"] }
serde_with = "3.13.0"
toml = "0.8"
